# Generated by Django 3.1.2 on 2020-10-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_mgr_rel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name_plural': 'Managers'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
