# Generated by Django 3.1.2 on 2020-10-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_mgr_rel', '0002_auto_20201003_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_name', to='emp_mgr_rel.employee'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
