# Generated by Django 3.1.2 on 2020-10-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_mgr_rel', '0004_auto_20201007_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='manager_name',
        ),
    ]
