# Generated by Django 3.1.2 on 2020-10-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=60)),
                ('manager_name', models.CharField(max_length=60)),
            ],
        ),
    ]
